<main id="createDishForm">
    <h2>Formulaire de création d'un plat</h2>
    <form action="/res03-projet-final/chef-we-chef-!/mon-compte/plat/creer" method="post" enctype="multipart/form-data">
        <fieldset>
            <label for="dishName">Nom du plat</label>
            <input type="text" name="dishName" id="dishName"/>
        </fieldset>
        <fieldset>
            <label for="image">Photo du plat</label>
            <input type="file" name="image" id="image"/>
        </fieldset>
        <fieldset>
            <label for="description">Description (250 charactères max)</label>
            <textarea name="description" id="description"></textarea>
        </fieldset>
        <fieldset>
            <label for="dishPrice">Prix par personne</label>
            <input type="text" name="dishPrice" id="dishPrice"/>
        </fieldset>
        <fieldset>
            <label for="dishFoodStyle">Style de cuisine</label>
            <select name="dishFoodStyle" id="dishFoodStyle">
                <option value="">--Choisir un style de cuisine--</option>
                <?php foreach($data["foodStyles"] as $foodstyle){ ?>
                <option value="<?= $foodstyle->getId() ?>"><?= $foodstyle->getName() ?></option>
                <?php } ?>
            </select>
        </fieldset>
        <fieldset>
            <label for="dishCategory">Catégorie</label>
            <select name="dishCategory" id="dishCategory">
                <option value="">--Choisir une catégorie--</option>
                <?php foreach($data["categories"] as $category){ ?>
                <option value="<?= $category->getId() ?>"><?= $category->getName() ?></option>
                <?php } ?>
            </select>
        </fieldset>
        <button type="submit">Enregistrer</button>
    </form>
</main>