<main id="events">
    </section>
        <section>
        <h2>Les disponibilités du chef <?= $data["chief"]->getChiefName(); ?></h2>



        <section class='agenda'>
            <h3><a href="?ym=<?= $data["calendar"]["preview"]; ?>"><span class="fa-solid fa-chevron-left"></span></a><?= $data["calendar"]["title"] ?><a href="?ym=<?= $data["calendar"]["next"]; ?>"><span class="fa-solid fa-chevron-right"></span></a></h3>
            <br>
            <table>
                <thead>
                    <tr>
                        <th><strong>Lundi</strong></th>
                        <th><strong>Mardi</strong></th>
                        <th><strong>Mercredi</strong></th>
                        <th><strong>Jeudi</strong></th>
                        <th><strong>Vendredi</strong></th>
                        <th><strong>Samedi</strong></th>
                        <th><strong>Dimanche</strong></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data["calendar"]["weeks"] as $week){
                        echo $week;
                    }?>
                </tbody>
            </table>

            <!--<a href="/res03-projet-final/chef-we-chef-!/mon-compte/calendar">Modifier mes disponibilités</a>-->

        </section>







    </section>
</main>