<main id="events">
    </section>
        <section id="chiefCalendar">
            <h2>Modifier mes disponibilités</h2>
    
            <section class='calendarByMonth'>
                <h3><a href="?ym=<?= $data["calendar"]["preview"]; ?>"><span class="fa-solid fa-chevron-left"></span></a><?= $data["calendar"]["title"] ?><a href="?ym=<?= $data["calendar"]["next"]; ?>"><span class="fa-solid fa-chevron-right"></span></a></h3>
                <br>
                <table>
                    <thead>
                        <tr>
                            <th><strong>Lundi</strong></th>
                            <th><strong>Mardi</strong></th>
                            <th><strong>Mercredi</strong></th>
                            <th><strong>Jeudi</strong></th>
                            <th><strong>Vendredi</strong></th>
                            <th><strong>Samedi</strong></th>
                            <th><strong>Dimanche</strong></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data["calendar"]["weeks"] as $week){
                            echo $week;
                        }?>
                    </tbody>
                </table>
            </section>
            
            <section class="calendarByWeek">
                <h3>Semaine du <?= $data['weekCalendar']['weekData']['day1']['dateStr']." ".$data['weekCalendar']['weekData']['day1']['year'] ?> au <?= $data['weekCalendar']['weekData']['day7']['dateStr']." ".$data['weekCalendar']['weekData']['day7']['year'] ?></h3>
                <section>
                    <a href="?date=<?= $data["weekCalendar"]["pastWeekDate"]."#chiefCalendar"; ?>"><span class="fa-solid fa-chevron-left"></span></a>
                    <a href="?date=<?= $data["weekCalendar"]["nextWeekDate"]."#chiefCalendar"; ?>"><span class="fa-solid fa-chevron-right"></span></a>
                </section>
                
                <section>
                    <?php foreach($data['weekCalendar']['weekData'] as $week){ ?>
                    <section>
                        <p><?= $week['day']." ".$week['dateStr'] ?></p>
                        <section>
                            <p class="event" date="<?= $week['date'] ?>-1">12:00</p>
                            <p class="event" date="<?= $week['date'] ?>-2">19:00</p>
                        </section>
                    </section>
                    <?php } ?>
                </section>
            </section>
            

        </section>

    </section>
</main>