<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Chef We Chef !</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />

</head>

<body>

    <header>
        <?php require 'partials/header.phtml'; ?>
    </header>    
    
    <main>
        <section>
            <?php 
                require "displays/".$template.".phtml"; 
            ?>
        </section>
    </main>
    
    <footer>
        <?php require 'partials/footer.phtml'; ?>
    </footer>

</body>
</html>