<!--<?php var_dump($data); ?>-->
<main id="profil">
    <section>
        <section>
            <figure>
                <img src="/res03-projet-final/chef-we-chef-!/<?= $data["chief"]->getProfilPictureUrl(); ?>" alt="Photo de profil"></img>
            </figure>
            <section>
                <h2>Chef <?= $data["chief"]->getChiefName(); ?></h2>
                <p><?= $data["chief"]->getDescription(); ?></p>
                <section>
                    <?php foreach($data["foodstyles"] as $foodstyle){ ?>
                    <p><?= $foodstyle->getName(); ?></p>
                    <?php } ?>
                </section>
            </section>
        </section>
        <a href="">Modifier le profil</a>

    </section>
    <section>
        <h2>Le menu du chef <?= $data["chief"]->getChiefName(); ?></h2>
        <section>
            <ul>
                <h3>Entrées</h3>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===1){?>
                <li>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </li>
                <?php }}?>

                <h3>Plats</h3>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===2){?>
                <li>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </li>
                <?php }} ?>

                <h3>Desserts</h3>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===3){?>
                <li>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </li>
                <?php }} ?>
            </ul>
        </section>
    </section>
    <section>
        <h2>Les réalisations du chef <?= $data["chief"]->getChiefName(); ?></h2>
        <section>
            <ul>
            <?php foreach ($data["dishes"] as $dish){ ?>
            <li>
                <figure>
                    <img src="<?= $dish->getPictureUrl() ?>" alt="Photo du plat">
                    <figcaption><?= $dish->getName() ?></figcaption>
                </figure>
            </li>
            <?php } ?>
            </ul>
            <a href="/res03-projet-final/chef-we-chef-!/mon-compte/plat/creer">Ajouter un plat</a>
        </section>
    </section>
        <section>
        <h2>Les disponibilités du chef <?= $data["chief"]->getChiefName(); ?></h2>



        <section>
            <h3><a href="?ym=<?= $data["calendar"]["preview"]; ?>"><</a><?= $data["calendar"]["title"] ?><a href="?ym=<?= $data["calendar"]["next"]; ?>">></a></h3>
            <br>
            <table>
                <thead>
                    <tr>
                        <th><strong>Lu</strong></th>
                        <th><strong>Ma</strong></th>
                        <th><strong>Me</strong></th>
                        <th><strong>Je</strong></th>
                        <th><strong>Ve</strong></th>
                        <th><strong>Sa</strong></th>
                        <th><strong>Di</strong></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data["calendar"]["weeks"] as $week){
                        echo $week;
                    }?>
                </tbody>
            </table>

            <a href="/res03-projet-final/chef-we-chef-!/mon-compte/calendar">Modifier mes disponibilités</a>

        </section>







    </section>

</main>