<!--<?php var_dump($data); ?>-->
<main id="profil">
    <section>
        <h2 class="hidden">Profil</h2>
        <section>
            <h3 class="hidden">Photo de profil</h3>
            <figure>
                <img src="/res03-projet-final/chef-we-chef-!/<?= $data["chief"]->getProfilPictureUrl(); ?>" alt="Photo de profil"/>
            </figure>
            <section>
                <h3>Chef <?= $data["chief"]->getChiefName(); ?></h3>
                <p><?= $data["chief"]->getDescription(); ?></p>
                <section>
                    <h4 class="hidden">Style de cuisine</h4>
                    <?php foreach($data["foodstyles"] as $foodstyle){ ?>
                    <p><?= $foodstyle->getName(); ?></p>
                    <?php } ?>
                </section>
            </section>
        </section>
        <a href="">Modifier le profil</a>

    </section>
    <section>
        <h2>Le menu du chef <?= $data["chief"]->getChiefName(); ?></h2>
        <section>
            <h3 class="hidden">Menu</h3>

            <section>
                <h4>Entrées</h4>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===1){?>
                <section>
                    <h5 class="hidden">Détail</h5>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </section>    
                <?php }}?>
            </section>

            <section>
                <h4>Plats</h4>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===2){?>
                <section>
                    <h5 class="hidden">Détail</h5>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </section>
                <?php }} ?>
            </section>

            <section>
                <h4>Desserts</h4>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===3){?>
                <section>
                    <h5 class="hidden">Détail</h5>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </section>
                <?php }} ?>
            </section>

        </section>
    </section>
    <section>
        <h2>Les réalisations du chef <?= $data["chief"]->getChiefName(); ?></h2>
        <section>
            <h3 class="hidden">Les photos</h3>
            <ul>
            <?php foreach ($data["dishes"] as $dish){ ?>
            <li>
                <figure>
                    <img src="<?= $dish->getPictureUrl() ?>" alt="Photo du plat"/>
                    <figcaption><?= $dish->getName() ?></figcaption>
                </figure>
            </li>
            <?php } ?>
            </ul>
            <a href="/res03-projet-final/chef-we-chef-!/mon-compte/plat/creer">Ajouter un plat</a>
        </section>
    </section>
    <section id="chiefCalendar">
        <h2>Les disponibilités du chef <?= $data["chief"]->getChiefName(); ?></h2>

        <section class='calendarByMonth'>
            <h3><a href="?ym=<?= $data["calendar"]["preview"]; ?>"><span class="fa-solid fa-chevron-left"></span></a><?= $data["calendar"]["title"] ?><a href="?ym=<?= $data["calendar"]["next"]; ?>"><span class="fa-solid fa-chevron-right"></span></a></h3>
            <table>
                <thead>
                    <tr>
                        <th><strong>Lundi</strong></th>
                        <th><strong>Mardi</strong></th>
                        <th><strong>Mercredi</strong></th>
                        <th><strong>Jeudi</strong></th>
                        <th><strong>Vendredi</strong></th>
                        <th><strong>Samedi</strong></th>
                        <th><strong>Dimanche</strong></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data["calendar"]["weeks"] as $week){
                        echo $week;
                    }?>
                </tbody>
            </table>
        </section>
        
        <section class="calendarByWeek">
            <h3>Semaine du <?= $data['weekCalendar']['weekData']['day1']['dateStr']." ".$data['weekCalendar']['weekData']['day1']['year'] ?> au <?= $data['weekCalendar']['weekData']['day7']['dateStr']." ".$data['weekCalendar']['weekData']['day7']['year'] ?></h3>
            <section>
                <h4 class="hidden">Changer de semaine</h4>
                <a href="?date=<?= $data["weekCalendar"]["pastWeekDate"]."#chiefCalendar"; ?>"><span class="fa-solid fa-chevron-left"></span></a>
                <a href="?date=<?= $data["weekCalendar"]["nextWeekDate"]."#chiefCalendar"; ?>"><span class="fa-solid fa-chevron-right"></span></a>
            </section>
            
            <section>
                <h4 class="hidden">Calendrier</h4>
                <?php foreach($data['weekCalendar']['weekData'] as $week){ ?>
                <section>
                    <h5 class="hidden">Jour</h5>
                    <p><?= $week['day']." ".$week['dateStr'] ?></p>
                    <section>
                        <h6 class="hidden">Créneaux</h6>
                        <p class="event" data-date="<?= $week['date'] ?>-1">12:00</p>
                        <p class="event" data-date="<?= $week['date'] ?>-2">19:00</p>
                    </section>
                </section>
                <?php } ?>
            </section>
        </section>

        <a href="/res03-projet-final/chef-we-chef-!/mon-compte/calendar">Modifier mes disponibilités</a>
    </section>

</main>