<!--<?php var_dump($data); ?>-->
<main id="profil">
    <section>
        <section>
            <figure>
                <img src="/res03-projet-final/chef-we-chef-!/<?= $data["chief"]->getProfilPictureUrl(); ?>" alt="Photo de profil"></img>
            </figure>
            <section>
                <h2>Chef <?= $data["chief"]->getChiefName(); ?></h2>
                <p><?= $data["chief"]->getDescription(); ?></p>
                <section>
                    <?php foreach($data["foodstyles"] as $foodstyle){ ?>
                    <p><?= $foodstyle->getName(); ?></p>
                    <?php } ?>
                </section>
            </section>
        </section>
        <a href="">Modifier le profil</a>

    </section>
    <section>
        <h2>Le menu du chef <?= $data["chief"]->getChiefName(); ?></h2>
        
        <section>
            <?php foreach($data["menu"] as $key=>$category){ ?>
            <ul>
                <h3><?= $key; ?></h3>
                
                <?php foreach($category as $element){ ?>
                <li>
                    <p><?= $element->getName(); ?></p>
                    <p><?= $element->getPrice(); ?> Euros/personne</p>
                </li>
                <?php } ?>
            </ul>
            <?php } ?>
        </section>
    </section>
    <section>
        <h2>Les réalisations du chef <?= $data["chief"]->getChiefName(); ?></h2>
        <section>
            <ul>
            <?php foreach ($data["dishes"] as $dish){ ?>
            <li>
                <figure>
                    <img src="<?= $dish->getPictureUrl() ?>" alt="Photo du plat">
                    <figcaption><?= $dish->getName() ?></figcaption>
                </figure>
            </li>
            <?php } ?>
            </ul>
            <a href="/res03-projet-final/chef-we-chef-!/mon-compte/plat/creer">Ajouter un plat</a>
        </section>
    </section>
</main>