<!--<?php var_dump($data); ?>-->
<main id="visitorChef">
    <section>
        <figure>
            <img src="<?= $data["chief"]->getProfilPictureUrl(); ?>" alt="Photo de profil"></img>
        </figure>
        <section>
            <h2>Chef <?= $data["chief"]->getChiefName(); ?></h2>
            <p><?= $data["chief"]->getDescription(); ?></p>
            <section>
                <?php foreach($data["foodstyles"] as $foodstyle){ ?>
                <p><?= $foodstyle->getName(); ?></p>
                <?php } ?>
            </section>
        </section>

    </section>
    <section>
        <h2>Le menu du chef <?= $data["chief"]->getChiefName(); ?></h2>
        
        <section>
            <?php foreach($data["menu"] as $key=>$category){ ?>
            <ul>
                <h3><?= $key; ?></h3>
                
                <?php foreach($category as $element){ ?>
                <li>
                    <p><?= $element->getName(); ?></p>
                    <p><?= $element->getPrice(); ?> Euros/personne</p>
                </li>
                <?php } ?>
            </ul>
            <?php } ?>
        </section>
    </section>
    <section>
        <h2>Les réalisations du chef <?= $data["chief"]->getChiefName(); ?></h2>
        <ul>
        <?php foreach ($data["dishes"] as $dish){ ?>
        <li>
            <figure>
                <img src="<?= $dish->getPictureUrl() ?>" alt="Photo du plat">
            </figure>
        </li>
        <?php } ?>
        </ul>
    </section>
</main>