<main id="visitorChiefs">
    <h2>Les chefs</h2>
    <ul>
        <?php foreach ($data as $chief){ ?>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="<?= $chief[0]->getProfilPictureUrl() ?>" alt="Photo de profil du chef">
                    </figure>
                </header>
                <section>
                    <h3>Chef <?= $chief[0]->getChiefName() ?></h3>
                    <p><?= $chief[0]->getDescription() ?></p>
                    <section>
                        <p><?= $chief[1]->getName() ?></p>
                        <p><?php if ($chief[2]!=="Pas de second style de cuisine") echo $chief[2]->getName() ?></p>
                    </section>
                </section>
                <footer>
                    <a href="chef/<?= $chief[0]->getId() ?>">Voir ce chef</a>
                </footer>
            </article>
        </li>
        <?php } ?>
    </ul>
</main>