<main id="visitorDishes">
    <h2>Les plats</h2>
    <ul>
        <?php foreach ($data as $dish){ ?>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="<?= $dish[0]->getPictureUrl() ?>" alt="Photo du plat">
                    </figure>
                    
                </header>
                <section>
                    <h3><?= $dish[0]->getName() ?></h3>
                    <p><?= $dish[0]->getDescription() ?></p>
                    <p>Prix/personne : <?= $dish[0]->getPrice() ?> Euros</p>
                    <p>Ceci est un(e) : <?= $dish[1]->getName() ?></p>
                    <p>Style de cuisine : <?= $dish[2]->getName() ?></p>
                </section>
            </article>
        </li>
        <?php } ?>
    </ul>
</main>