<main id="loginForm">
    <h2>Formulaire de connexion</h2>
    <form action="/res03-projet-final/chef-we-chef-!/connexion" method="post">
        <fieldset>
            <label for="">Email</label>
            <input type="email" name="loginEmail"/>
        </fieldset>
        <fieldset>
            <label for="">Mot de passe</label>
            <input type="password" name="loginPassword"/>
        </fieldset>
        <button type="submit">Connexion</button>
    </form>
</main>
