<main>
    <h2>Formulaire de création de compte</h2>
    <form action="/res03-projet-final/chef-we-chef-!/inscription" method="post">
        <fieldset>
            <label for="">Prénom</label>
            <input type="text" name="firstName"/>
        </fieldset>
        <fieldset>
            <label for="">Nom</label>
            <input type="text" name="lastName"/>
        </fieldset>
        <fieldset>
            <label for="">Pseudo de chef</label>
            <input type="text" name="chiefName"/>
        </fieldset>
        <fieldset>
            <label for="">Email</label>
            <input type="email" name="email"/>
        </fieldset>
        <fieldset>
            <label for="">Mot de passe</label>
            <input type="password" name="firstPassword"/>
        </fieldset>
        <fieldset>
            <label for="">Vérification du mot de passe</label>
            <input type="password" name="secondPassword"/>
        </fieldset>
        <fieldset>
            <label for="">Phone</label>
            <input type="text" name="phone"/>
        </fieldset>
        <fieldset>
            <label for="">Photo de profil</label>
            <input type="text" name="picture"/>
        </fieldset>
        <fieldset>
            <label for="">Description</label>
            <input type="textarea" name="description"/>
        </fieldset>
        <fieldset>
            <label for="">Style de cuisine 1</label>
            <select name="firstFoodStyle">
                <option value="">--Choisir un style de cuisine--</option>
                <?php foreach($data as $foodstyle){ ?>
                <option value="<?= $foodstyle->getId() ?>"><?= $foodstyle->getName() ?></option>
                <?php } ?>
            </select>
        </fieldset>
        <fieldset>
            <label for="">Style de cuisine 2</label>
            <select name="secondFoodStyle">
                <option value="">--Choisir un style de cuisine--</option>
                <?php foreach($data as $foodstyle){ ?>
                <option value="<?= $foodstyle->getId() ?>"><?= $foodstyle->getName() ?></option>
                <?php } ?>
            </select>
        </fieldset>
        <button type="submit">Enregistrer</button>
    </form>
</main>