<main>
    <h2>Formulaire de création de compte</h2>
    <from>
        <fieldset>
            <label for="">Prénom</label>
            <input type="text" name=""/>
        </fieldset>
        <fieldset>
            <label for="">Nom</label>
            <input type="text" name=""/>
        </fieldset>
        <fieldset>
            <label for="">Pseudo de chef</label>
            <input type="text" name=""/>
        </fieldset>
        <fieldset>
            <label for="">Nom de la société (facultatif)</label>
            <input type="text" name=""/>
        </fieldset>
        <fieldset>
            <label for="">Email</label>
            <input type="text" name=""/>
        </fieldset>
        <fieldset>
            <label for="">Phone</label>
            <input type="text" name=""/>
        </fieldset>
        <fieldset>
            <label for="">Photo de profil</label>
            <input type="text" name=""/>
        </fieldset>
        <fieldset>
            <label for="">Description</label>
            <input type="textarea" name=""/>
        </fieldset>
    </from>
</main>
