<aside id="visitor_aside" class='hidden'>
    <h2 class="hidden">Menu petit écran</h1>
    <ul>
        <li>
            <figure>
                <img src="/res03-projet-final/chef-we-chef-!/<?= $_SESSION["chiefPicture"] ?>" alt="Photo du profil"/>
            </figure>
        </li>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/deconnexion">Déconnexion</a>
        </li>

    </ul>
    <nav>
        <h3 class="hidden">Menu de navigation</h3>
        <ul>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/">Accueil</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/chefs">Les chefs</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/plats">Les plats</a>
            </li>                
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/mon-compte">Mon profil</a>
            </li>                
        </ul>
    </nav>
</aside>
