<header id="visitor_header">
    <h1 class="hidden">Chef we chef !</h1>
    <figure>
        <img src="/res03-projet-final/chef-we-chef-!/assets/img/2.png" alt="Logo du site"/>
    </figure>
    <nav>
        <h2 class="hidden">Menu de navigation</h2>
        <ul>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/">Accueil</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/chefs">Les chefs</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/plats">Les plats</a>
            </li>                
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/mon-compte">Mon profil</a>
            </li>                
        </ul>
    </nav>
    <ul>
        <li>
            <figure>
                <img src="/res03-projet-final/chef-we-chef-!/<?= $_SESSION["chiefPicture"] ?>" alt="Photo du profil"/>
            </figure>
        </li>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/deconnexion">Déconnexion</a>
        </li>

    </ul>
    <span id='menuBtn' class="fa-solid fa-bars"></span>
</header>
