<header id="visitor_header">
    <figure>
        <img src="/res03-projet-final/chef-we-chef-!/assets/img/2.png"></img>
    </figure>
    <nav>
        <ul>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/">Accueil</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/chefs">Les chefs</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/plats">Les plats</a>
            </li>                
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/plats">Mon profil</a>
            </li>                
        </ul>
    </nav>
    <ul>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/deconnexion">Se déconnecter</a>
        </li>
    </ul>
</header>
