<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/res03-projet-final/chef-we-chef-!/admin">ADMIN</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/res03-projet-final/chef-we-chef-!/admin">Les chefs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/res03-projet-final/chef-we-chef-!/admin/plats">Les plats</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/res03-projet-final/chef-we-chef-!/admin/styles-de-cuisine">Les styles de cuisine</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/res03-projet-final/chef-we-chef-!/admin/categories">Les catégories</a>
                    </li>
                </ul>

            </div>
                <a href="/res03-projet-final/chef-we-chef-!/deconnexion">Se déconnecter</a>
        </div>
    </nav>
</header>