<aside id="visitor_aside" class='hidden'>
    <ul>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/connexion">Connection</a>
        </li>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/inscription">Inscription</a>
        </li>
    </ul>
    <nav>
        <ul>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/home">Accueil</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/chefs">Les chefs</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/plats">Les plats</a>
            </li>                
        </ul>
    </nav>
</aside>
