<footer id="footer">
    <section>
        <h2 class="hidden">Pied de page</h2>
        <section>
            <h3>Nous contacter</h3>
            <form action="/res03-projet-final/chef-we-chef-!/contactUs" id="contactUsForm" method="post">
                <fieldset>
                    <label for="contactEmail">Votre email</label>
                    <input type="email" name="contactEmail" id="contactEmail"/>
                    <small id="contactEmailError">Merci de rentrer un titre valide</small>
                </fieldset>
                <fieldset>
                    <label for="contactSubject">Sujet</label>
                    <input type="text" name="contactSubject" id="contactSubject"/>
                    <small id="contactSubjectError">Merci de rentrer un titre valide</small>
                </fieldset>
                <fieldset>
                    <label for="contactDescription">Description</label>
                    <textarea name="contactDescription" id="contactDescription"></textarea>
                    <small id="contactDescriptionError">Merci de rentrer un titre valide</small>
                </fieldset>
                <button type="submit">Envoyer</button>
            </form>
        </section>
        <section>
            <h3>Mentions légales</h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </section>

    </section>
    <section>
        <h3>© 2023 by Vincent Ollivier - Développeur Web à Rennes</h3>
    </section>
</footer>