<header id="visitor_header">
    <h1 class="hidden">Chef we chef !</h1>
    <figure>
        <img src="/res03-projet-final/chef-we-chef-!/assets/img/2.png" alt="Logo du site"/>
    </figure>
    <span id='menuBtn' class="fa-solid fa-bars"></span>
    <nav>
        <h2 class="hidden">Menu de navigation</h2>
        <ul>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/home">Accueil</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/chefs">Les chefs</a>
            </li>
            <li>
                <a href="/res03-projet-final/chef-we-chef-!/plats">Les plats</a>
            </li>                
        </ul>
    </nav>
    <ul>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/connexion">Connexion</a>
        </li>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/inscription">Inscription</a>
        </li>
    </ul>
</header>
