<!--<?php var_dump($data) ?>-->
<main>
    <h2 class="text-center m-5 h2 adminTitles">Les catégories</h2>
    <section class="d-flex flex-column align-items-center">
        <h3 class="hidden">Tableau</h3>
        <a href="categories/creer" class="btn btn-primary mb-3">Nouvelle catégorie</a>
        <table class="table col-10 table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Fonctions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($data as $category){ ?>
                <tr>
                    <td><?= $category->getId() ?></td>
                    <td><?= $category->getName() ?></td>
                    <td>
                        <a href="categorie&id=<?= $category->getId() ?>"><span class="fa-solid fa-eye"></span></a>
                        <a href="modifier-categorie&id=<?= $category->getId() ?>"><span class="fa-solid fa-pen"></span></a>
                        <a href="supprimer-categorie&id=<?= $category->getId() ?>"><span class="fa-solid fa-trash"></span></a>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </section>
</main>