<!--<?php var_dump($data) ?>-->
<main>
    <h2 class="text-center m-5">Modifier la catégorie</h2>
    
    <section class="d-flex justify-content-center">
    <h3 class="hidden">Formulaire</h3>

        <form action="/res03-projet-final/chef-we-chef-!/admin/modifier-categorie&id=<?= $data["category"]->getId() ?>" method="post" class="col-4">
        
            <section class="mb-3">
                <h4 class="hidden">Champ</h4>
                <fieldset>
                    <label class="form-label">Nom</label>
                    <input class="form-control" type="text" name="categoryName" value="<?= $data["category"]->getName() ?>"/>
                </fieldset>
            </section>
            
            <button class="btn btn-primary">Modifier</button>
        
        </form>
        
        
    </section>
</main>