<!--<?php var_dump($data) ?>-->
<main>
    <h2 class="text-center m-5">Catégorie</h2>
    <section class="d-flex flex-column align-items-center">
        <table class="table col-10 table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($data as $category){ ?>
                <tr>
                    <td><?= $category->getId() ?></td>
                    <td><?= $category->getName() ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </section>
</main>