<!--<?php var_dump($data); ?>-->
<main>
    <h2 class="text-center m-5 h2 adminTitles">Les chefs</h2>
    <section class="d-flex flex-column align-items-center">
        <h3 class="hidden">Tableau</h3>
        <table class="table col-10 table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Téléphone</th>
                    <th>Photo de profil</th>
                    <th>Déscritpion</th>
                    <th>Style de cuisine</th>
                    <th>Fonctions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($data as $chief){ ?>
                <tr>
                    <td><?= $chief["chief"]->getId() ?></td>
                    <td><?= $chief["chief"]->getFirstName() ?></td>
                    <td><?= $chief["chief"]->getLastName() ?></td>
                    <td><?= $chief["chief"]->getEmail() ?></td>
                    <td><?= $chief["chief"]->getPhone() ?></td>
                    <td><?= $chief["chief"]->getProfilPictureUrl() ?><img src="/res03-projet-final/chef-we-chef-!/<?= $chief["chief"]->getProfilPictureUrl() ?>" class="adminImage" alt="Photo de profil du chef"/></td>
                    <td><?= $chief["chief"]->getDescription() ?></td>
                    <td><?= $chief["foodStyle"][0]->getName() ?> (id=<?= $chief["chief"]->getFoodStyleId() ?>)</td>
                    <td>
                        <a href="admin/chef&id=<?= $chief["chief"]->getId() ?>"><i class="fa-solid fa-eye"></i></a>
                        <a href="admin/supprimer-chef&id=<?= $chief["chief"]->getId() ?>"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </section>
</main>