<!--<?php var_dump($data); ?>-->
<main id="adminChefs">
    <h2>Les chefs</h2>
    <table class="table table-striped">
        <thead>
            <tr class="conteneur">
                <th>Id</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Téléphone</th>
                <th>URL de la photo de profil</th>
                <th>Déscritpion</th>
                <th>Premier style de cuisine</th>
                <th>Second style de cuisine</th>
                <th>Fonctions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($data as $chief){ ?>
            <tr>
                <td><?= $chief[0]->getId() ?></td>
                <td><?= $chief[0]->getFirstName() ?></td>
                <td><?= $chief[0]->getLastName() ?></td>
                <td><?= $chief[0]->getEmail() ?></td>
                <td><?= $chief[0]->getPhone() ?></td>
                <td><?= $chief[0]->getProfilPictureUrl() ?></td>
                <td><?= $chief[0]->getDescription() ?></td>
                <td><?= $chief[0]->getFirstFoodStyleId() ?></td>
                <td><?= $chief[0]->getSecondFoodStyleId() ?></td>
                <td>
                    <a href=""><i class="fa-solid fa-eye"></i></a>
                    <a href=""><i class="fa-solid fa-pen"></i></a>
                    <a href=""><i class="fa-solid fa-trash"></i></a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</main>