<!--<?php var_dump($data) ?>-->
<main>
    <h2 class="text-center m-5">Les plats</h2>
    <section class="d-flex flex-column align-items-center">
        <h3 class="hidden">Tableau</h3>
        <table class="table col-10 table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Photo du plat</th>
                    <th>Déscritpion</th>
                    <th>Prix/personne</th>
                    <th>Id du chef</th>
                    <th>Id du style de cuisine</th>
                    <th>Id de la catégorie</th>
                    <th>Fonctions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($data as $dish){ ?>
                <tr>
                    <td><?= $dish["dish"]->getId() ?></td>
                    <td><?= $dish["dish"]->getName() ?></td>
                    <td><?= $dish["dish"]->getPictureUrl() ?><img src="/res03-projet-final/chef-we-chef-!/<?= $dish["dish"]->getPictureUrl() ?>" class="adminImage" alt="Photo du plat"/></td>
                    <td><?= $dish["dish"]->getDescription() ?></td>
                    <td><?= $dish["dish"]->getPrice() ?></td>
                    <td><?= $dish["chief"]->getChiefName() ?> (id=<?= $dish["dish"]->getChiefId() ?>)</td>
                    <td><?= $dish["foodStyle"]->getName() ?> (id=<?= $dish["dish"]->getFoodStyleId() ?>)</td>
                    <td><?= $dish["category"]->getName() ?> (id=<?= $dish["dish"]->getCategoryId() ?>)</td>
                    <td>
                        <a href="plat&id=<?= $dish["dish"]->getId() ?>"><i class="fa-solid fa-eye"></i></a>
                        <a href="supprimer-plat&id=<?= $dish["dish"]->getId() ?>"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </section>
</main>