<main>
    <h2 class="text-center m-5">Nouveau style de cuisine</h2>
    <form action="/res03-projet-final/chef-we-chef-!/admin/styles-de-cuisine/creer" method="post">
        <fieldset>
            <label>Nom</label>
            <input type="text" name="foodStyleName"/>
        </fieldset>
        <fieldset>
            <label>Description</label>
            <input type="text" name="foodStyleDescription"/>
        </fieldset>
        <button>Créer</button>
    </form>
</main>