<!--<?php var_dump($data) ?>-->
<main>
    <h2 class="text-center m-5">Style de cuisine</h2>
    <section class="d-flex flex-column align-items-center">
        <h3 class="hidden">Tableau</h3>
        <table class="table col-10 table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Déscritpion</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($data as $foodStyle){ ?>
                <tr>
                    <td><?= $foodStyle->getId() ?></td>
                    <td><?= $foodStyle->getName() ?></td>
                    <td><?= $foodStyle->getDescription() ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </section>
</main>