<footer>
    <section>
        <section>
            <h2>Mention legale</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </section>
        <section>
            <h2>Nous contacter</h2>
            <form action="" method="">
                <fieldset>
                    <label for="">Sujet</label>
                    <input type="text" name=""/>
                </fieldset>
                <fieldset>
                    <label for="">Description</label>
                    <input type="textarea" name=""/>
                </fieldset>
            </form>
        </section>
    </section>
    <section>
        <p>Créer par Vincent Ollivier</p>
    </section>
</footer>