<header>
    <h2>Header</h2>
    <ul>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/">Accueil</a>
            <a href="/res03-projet-final/chef-we-chef-!/chefs">Les chefs</a>
            <a href="/res03-projet-final/chef-we-chef-!/plats">Les plats</a>
        </li>
    </ul>
    <ul>
        <li>
            <a href="/res03-projet-final/chef-we-chef-!/connexion">Se connecter</a>
            <a href="/res03-projet-final/chef-we-chef-!/inscription">S'inscrire</a>
        </li>
    </ul>
</header>
