<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Chef We Chef !</title>

    <!--<meta name="viewport" content="width=device-width, initial-scale=1" />-->
    <link rel="stylesheet" href="/res03-projet-final/chef-we-chef-!/assets/styles/css/style.css" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/dbf8b52bf4.js" crossorigin="anonymous"></script>

    <!--// Calendar-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="css/style.css">
    

</head>

<body>
    
    <?php
    if(isset($_SESSION) && !empty($_SESSION) && $_SESSION["connected"] && $_SESSION["role"]==="chief"){
        require 'partials/accountHeader.phtml';
        require $template.".phtml";
        require 'partials/footer.phtml';
    }

    else if(isset($_SESSION) && !empty($_SESSION) && $_SESSION["connected"] && $_SESSION["role"]==="admin"){
        require 'partials/adminHeader.phtml';
        require $template.".phtml";
    }
    else{
        require 'partials/header.phtml';
        require $template.".phtml";
        require 'partials/footer.phtml';
    }
    ?>

</body>
</html>