<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Chef We Chef !</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="/res03-projet-final/chef-we-chef-!/assets/styles/css/style.css" type="text/css" />

</head>

<body>
    
    <?php
    if(isset($_SESSION) && !empty($_SESSION) && $_SESSION["connected"] && $_SESSION["role"]==="chief"){
        require 'partials/accountHeader.phtml';
    }
    else{
        require 'partials/header.phtml';
    }
    ?>

    <?php require $template.".phtml"; ?>

    <?php require 'partials/footer.phtml'; ?>

</body>
</html>