<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Chef We Chef !</title>

        <meta name="title" content="Chef We Chef ! - Chef à domicile"/>
        <meta name="description" content="Proposez vos services de cuisinier pour les particuliers"/>
        <meta name="keywords" content="cuisinier,chef,cuisine,domicile,maison,manger,restaurant"/>
        <meta name="author" content="Vincent Ollivier"/>
        <meta name="referrer" content="origin"/>
        
        <meta property="og:title" content="Chef We Chef ! - Chef à domicile"/>
        <meta property="og:type" content="Plateforme"/>
        <meta property="og:image" content="/res03-projet-final/chef-we-chef-!/assets/img/2.png" />
        <meta property="og:url" content="http://vincentollivier.sites.3wa.io/res03-projet-final/chef-we-chef-!/"/>
        <meta property="og:description" content="Proposez vos services de cuisinier pour les particuliers"/>
        <meta property="og:locale" content="fr_FR"/>
        <meta property="og:site_name" content="Chef We Chef !"/>

    
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/dbf8b52bf4.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://vincentollivier.sites.3wa.io/res03-projet-final/chef-we-chef-!/assets/styles/css/style.css" type="text/css" />
    
        <!--// Calendar-->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    	<link rel="stylesheet" href="css/style.css">
        
        <!--Polices d'écriture-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">

    
    </head>

<body>
    
    <?php
    if(isset($_SESSION) && !empty($_SESSION) && $_SESSION["connected"] && $_SESSION["role"]==="chief"){
        require 'partials/accountHeader.phtml';
        require 'partials/accountAside.phtml';
        require $template.".phtml";
        require 'partials/footer.phtml';
    }

    else if(isset($_SESSION) && !empty($_SESSION) && $_SESSION["connected"] && $_SESSION["role"]==="admin"){
        require 'partials/adminHeader.phtml';
        require $template.".phtml";
    }
    else{
        require 'partials/header.phtml';
        require 'partials/aside.phtml';
        require $template.".phtml";
        require 'partials/footer.phtml';
    }
    ?>
    
<script type="module" src="/res03-projet-final/chef-we-chef-!/assets/js/index.js"></script>
</body>
</html>