<!--<?php var_dump($data); ?>-->
<main id="visitorChiefs">
    <h2>Les chefs</h2>
    <ul>
        <?php foreach ($data as $chief){ ?>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="<?= $chief["chief"]->getProfilPictureUrl() ?>" alt="Photo de profil du chef">
                    </figure>
                </header>
                <section>
                    <h3>Chef <?= $chief["chief"]->getChiefName() ?></h3>
                    <p><?= $chief["chief"]->getDescription() ?></p>
                    <p><?= $chief["foodStyle"][0]->getName() ?></p>
                </section>
                <footer>
                    <a href="chef&id=<?= $chief["chief"]->getId() ?>">Voir ce chef</a>
                </footer>
            </article>
        </li>
        <?php } ?>
    </ul>
</main>