<!--<?php var_dump($data); ?>-->
<main id="visitorChef">
    <section>
        <figure>
            <img src="/res03-projet-final/chef-we-chef-!/<?= $data["chief"]->getProfilPictureUrl(); ?>" alt="Photo de profil"></img>
        </figure>
        <section>
            <h2>Chef <?= $data["chief"]->getChiefName(); ?></h2>
            <p><?= $data["chief"]->getDescription(); ?></p>
            <section>
                <?php foreach($data["foodstyles"] as $foodstyle){ ?>
                <p><?= $foodstyle->getName(); ?></p>
                <?php } ?>
            </section>
        </section>

    </section>
    <section>
        <h2>Le menu du chef <?= $data["chief"]->getChiefName(); ?></h2>
        <section>
            <ul>
                <h3>Entrées</h3>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===1){?>
                <li>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </li>
                <?php }}?>

                <h3>Plats</h3>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===2){?>
                <li>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </li>
                <?php }} ?>

                <h3>Desserts</h3>
                <?php foreach($data["dishes"] as $dich){
                    if ($dich->getCategoryId()===3){?>
                <li>
                    <p><?= $dich->getName(); ?></p>
                    <p><?= $dich->getPrice(); ?> Euros/personne</p>
                </li>
                <?php }} ?>
            </ul>
        </section>
    </section>
    <section>
        <h2>Les réalisations du chef <?= $data["chief"]->getChiefName(); ?></h2>
        <ul>
        <?php foreach ($data["dishes"] as $dish){ ?>
        <li>
            <figure>
                <img src="/res03-projet-final/chef-we-chef-!/<?= $dish->getPictureUrl() ?>" alt="Photo du plat">
                <figcaption><?= $dish->getName() ?></figcaption>
            </figure>
        </li>
        <?php } ?>
        </ul>
    </section>

    <section>
        <h2>Les disponibilités du chef <?= $data["chief"]->getChiefName(); ?></h2>

        <section class='agenda'>
            <h3><a href="?ym=<?= $data["calendar"]["preview"]; ?>"><span class="fa-solid fa-chevron-left"></span></a><?= $data["calendar"]["title"] ?><a href="?ym=<?= $data["calendar"]["next"]; ?>"><span class="fa-solid fa-chevron-right"></span></a></h3>
            <br>
            <table>
                <thead>
                    <tr>
                        <th><strong>Lundi</strong></th>
                        <th><strong>Mardi</strong></th>
                        <th><strong>Mercredi</strong></th>
                        <th><strong>Jeudi</strong></th>
                        <th><strong>Vendredi</strong></th>
                        <th><strong>Samedi</strong></th>
                        <th><strong>Dimanche</strong></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data["calendar"]["weeks"] as $week){
                        echo $week;
                    }?>
                </tbody>
            </table>


        </section>
        
        <section class="calendarByWeek">
            <h3><a href="?ym=<?= $data["calendar"]["preview"]; ?>"><span class="fa-solid fa-chevron-left"></span></a>Semaine du <?= $data['week'][0][1] ?> au <?= $data['week'][6][1] ?><a href="?ym=<?= $data["calendar"]["next"]; ?>"><span class="fa-solid fa-chevron-right"></span></a></h3>
            
            <section>
                <section>
                    <p>Lundi <?= $data['week'][0][1] ?></p>
                    <section>
                        <p class="event" date="<?= $data['week'][0][0] ?>-1">12:00</p>
                        <p class="event" date="<?= $data['week'][0][0] ?>-2">19:00</p>
                    </section>
                </section>
                <section>
                    <p>Mardi <?= $data['week'][1][1] ?></p>
                    <section>
                        <p class="event" date="<?= $data['week'][1][0] ?>-1">12:00</p>
                        <p class="event" date="<?= $data['week'][1][0] ?>-2">19:00</p>
                    </section>
                </section>
                <section>
                    <p>Mercredi <?= $data['week'][2][1] ?></p>
                    <section>
                        <p class="event" date="<?= $data['week'][2][0] ?>-1">12:00</p>
                        <p class="event" date="<?= $data['week'][2][0] ?>-2">19:00</p>
                    </section>
                </section>
                <section>
                    <p>Jeudi <?= $data['week'][3][1] ?></p>
                    <section>
                        <p class="event" date="<?= $data['week'][3][0] ?>-1">12:00</p>
                        <p class="event" date="<?= $data['week'][3][0] ?>-2">19:00</p>
                    </section>
                </section>
                <section>
                    <p>Vendredi <?= $data['week'][4][1] ?></p>
                    <section>
                        <p class="event" date="<?= $data['week'][4][0] ?>-1">12:00</p>
                        <p class="event" date="<?= $data['week'][4][0] ?>-2">19:00</p>
                    </section>
                </section>
                <section>
                    <p>Samedi <?= $data['week'][5][1] ?></p>
                    <section>
                        <p class="event" date="<?= $data['week'][5][0] ?>-1">12:00</p>
                        <p class="event" date="<?= $data['week'][5][0] ?>-2">19:00</p>
                    </section>
                </section>
                <section>
                    <p>Dimanche <?= $data['week'][6][1] ?></p>
                    <section>
                        <p class="event" date="<?= $data['week'][6][0] ?>-1">12:00</p>
                        <p class="event" date="<?= $data['week'][6][0] ?>-2">19:00</p>
                    </section>
                </section>
            </section>
        </section>
    </section>
</main>