<!--<?php var_dump($data) ?>-->
<main id="visitorDishes">
    <h2>Les plats</h2>
    <ul>
        <?php foreach ($data as $dish){ ?>
        <li>
            <article>
                <header>
                    <figure>
                        <img src="<?= $dish["dish"]->getPictureUrl(); ?>" alt="Photo du plat">
                    </figure>
                </header>
                <section>
                    <h3><?= $dish["dish"]->getName() ?></h3>
                    <p><?= $dish["dish"]->getDescription() ?></p>
                    <p>Prix/personne : <?= $dish["dish"]->getPrice(); ?> Euros</p>
                    <p>Ceci est un(e) : <?= $dish["category"]->getName(); ?></p>
                    <p>Style de cuisine : <?= $dish["foodStyle"]->getName(); ?></p>
                </section>
                <footer>
                    <figure>
                        <img src="<?= $dish["chief"]->getProfilPictureUrl(); ?>" alt="Photo du chef"></img>
                        <figcaption><a href="chef&id=<?= $dish["chief"]->getId() ?>">Chef <?= $dish["chief"]->getChiefName(); ?></a></figcaption>
                    </figure>

                </footer>
            </article>
        </li>
        <?php } ?>
    </ul>
</main>