<!--<?php var_dump($data); ?>-->
<main id="visitorHome">
    <section>
        <h1>CHEF WE CHEF !</h1>
    </section>
    
    <section>
        <h2>A propos</h2>
        <p>CHEF WE CHEF ! est un site qui permet à des chefs cuisiniers de s'inscrire pour proposer leurs services à domicile. Les utilisateurs peuvent alors consulter les profils des chefs disponibles à la date de leur choix et réserver les services de leur choix.</p>
        
        <p>Ce site comporte plusieurs fonctionnalités pour les chefs inscrits, comme la création d'un profil avec des informations sur leurs compétences culinaires, leurs expériences, leurs tarifs et leurs disponibilités. Les chefs peuvent également ajouter des photos de leurs réalisations avec des informations sur leurs plats.</p>

        <p>Les utilisateurs quand à eux peuvent consulter les chefs disponibles à la date et l'heure de leur choix. Ils peuvent également consulter les profils des chefs pour voir leurs menu et leurs tarifs. Les utilisateurs peuvent alors prendre contact avec le chef selectionné pour définir des dernière formalité.

        <p>En résumé, ce site permet à des chefs à domicile de proposer leurs services de cuisine à domicile et à des utilisateurs de réserver un chef pour préparer un repas à leur domicile à une date et une heure spécifiques.</p>
    </section>
    <section>
        <h2>Les derniers chefs</h2>
        <ul>
            <?php foreach ($data as $chief){ ?>
            <li>
                <article>
                    <h3 class='hidden'>Article d'un chef</h3>
                    <header>
                        <figure>
                            <img src="<?= $chief["chief"]->getProfilPictureUrl() ?>" alt="Photo de profil du chef"/>
                        </figure>
                    </header>
                    <section>
                        <h4>Chef <?= $chief["chief"]->getChiefName() ?></h4>
                        <p><?= $chief["chief"]->getDescription() ?></p>
                        <p><?= $chief["foodStyle"][0]->getName() ?></p>
                    </section>
                    <footer>
                        <a href="chef&id=<?= $chief["chief"]->getId() ?>">Voir ce chef</a>
                    </footer>

                </article>
            </li>
            <?php } ?>
        </ul>
    </section>
    <section>
        <h2>Comment devenir Chef avec "Chef We Chef !" ?</h2>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    
        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
    </section>
</main>