<!--<?php var_dump($data); ?>-->
<main id="visitorHome">
    <section>
        <h1>CHEF WE CHEF !</h1>
    </section>
    
    <section>
        <h2>A propos</h2>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    
        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
    </section>
    <section>
        <h2>Les derniers chefs</h2>
        <ul>
            <?php foreach ($data as $chief){ ?>
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="<?= $chief["chief"]->getProfilPictureUrl() ?>" alt="Photo de profil du chef">
                        </figure>
                    </header>
                    <section>
                        <h3>Chef <?= $chief["chief"]->getChiefName() ?></h3>
                        <p><?= $chief["chief"]->getDescription() ?></p>
                        <section>
                            <p><?= $chief["foodStyle"][0]->getName() ?></p>
                            <p><?php if ($chief["foodStyle"][1]!=="Pas de second style de cuisine") echo $chief["foodStyle"][1]->getName() ?></p>
                        </section>
                    </section>
                    <footer>
                        <a href="chef/<?= $chief["chief"]->getId() ?>">Voir ce chef</a>
                    </footer>

                </article>
            </li>
            <?php } ?>
        </ul>
    </section>
    <section>
        <h2>Comment devenir Chef avec "Chef We Chef !" ?</h2>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    
        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
    </section>
</main>