<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Chef We Chef !</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="assets/styles/css/style.css" type="text/css" />

</head>

<body>

    <?php require 'partials/header.phtml'; ?>

    <?php require "displays/".$template.".phtml"; ?>

    <?php require 'partials/footer.phtml'; ?>

</body>
</html>