<main id="loginForm">
    <h2>Formulaire de connexion</h2>
    <p><?= $data['errorMessage'] ?></p>

    <form action="/res03-projet-final/chef-we-chef-!/connexion" id="login" method="post">
        <fieldset>
            <label for="loginEmail">Email</label>
            <input type="text" name="loginEmail" id="loginEmail"/>
            <small id="loginEmailError">Merci de rentrer un email valide</small>
        </fieldset>
        <fieldset>
            <label for="loginPassword">Mot de passe</label>
            <input type="password" name="loginPassword" id="loginPassword"/>
            <small id="loginPasswordError">Merci de rentrer votre mot de passe</small>
        </fieldset>
        <button type="submit">Connexion</button>
    </form>
</main>
